apiVersion: v2
name: grocery-app
description: A production-grade Helm chart for the Grocery Hub microservices platform
type: application
version: 1.0.0
appVersion: "1.0.0"

maintainers:
  - name: biswajit134
    url: https://github.com/biswajit134

keywords:
  - grocery
  - microservices
  - nodejs
  - istio
  - mongodb
  - redis

home: https://github.com/biswajit134/Grocery-app
sources:
  - https://github.com/biswajit134/Grocery-app
