apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-partner
  namespace: client
  labels:
    app: delivery-partner
    app.kubernetes.io/part-of: groceryhub
spec:
  replicas: 2
  selector:
    matchLabels:
      app: delivery-partner
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: delivery-partner
        app.kubernetes.io/part-of: groceryhub
    spec:
      containers:
        - name: delivery-partner
          image: biswajit134/grocery-delivery-app:latest
          ports:
            - containerPort: 3001
              protocol: TCP
          env:
            - name: VITE_AUTH_URL
              valueFrom:
                configMapKeyRef:
                  name: client-config
                  key: VITE_AUTH_URL
            - name: VITE_ORDER_URL
              valueFrom:
                configMapKeyRef:
                  name: client-config
                  key: VITE_ORDER_URL
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 150m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: delivery-partner
  namespace: client
  labels:
    app: delivery-partner
    app.kubernetes.io/part-of: groceryhub
spec:
  type: ClusterIP
  selector:
    app: delivery-partner
  ports:
    - port: 3001
      targetPort: 3001
      protocol: TCP
      name: http
