{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ include "grocery-app.fullname" . }}-gateway
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "grocery-app.labels" . | nindent 4 }}
spec:
  selector:
    istio: {{ .Values.istio.gateway.ingressGatewaySelector }}
  servers:
    {{- range .Values.istio.gateway.servers }}
    - port:
        number: {{ .port.number }}
        name: {{ .port.name }}
        protocol: {{ .port.protocol }}
      hosts:
        - {{ $.Values.global.domain | quote }}
      {{- if .tls }}
      tls:
        mode: {{ .tls.mode }}
        credentialName: {{ .tls.credentialName }}
      {{- end }}
    {{- end }}
{{- end }}
