apiVersion: v1
kind: Secret
metadata:
  name: {{ include "grocery-app.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "grocery-app.labels" . | nindent 4 }}
type: Opaque
data:
  jwt-secret: {{ .Values.secrets.jwtSecret | b64enc | quote }}
  {{- if or .Values.mongodb.enabled .Values.secrets.mongoUri.auth }}
  mongo-uri-auth: {{ include "grocery-app.mongoUri" (dict "context" . "database" "grocery_auth" "secretKey" "auth") | b64enc | quote }}
  {{- end }}
  {{- if or .Values.mongodb.enabled .Values.secrets.mongoUri.products }}
  mongo-uri-products: {{ include "grocery-app.mongoUri" (dict "context" . "database" "grocery_products" "secretKey" "products") | b64enc | quote }}
  {{- end }}
  {{- if or .Values.mongodb.enabled .Values.secrets.mongoUri.orders }}
  mongo-uri-orders: {{ include "grocery-app.mongoUri" (dict "context" . "database" "grocery_orders" "secretKey" "orders") | b64enc | quote }}
  {{- end }}
