{{- if .Values.deliveryPartner.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "grocery-app.componentName" (dict "context" . "component" "delivery-partner") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "grocery-app.componentLabels" (dict "context" . "component" "delivery-partner") | nindent 4 }}
spec:
  type: {{ .Values.deliveryPartner.service.type }}
  ports:
    - port: {{ .Values.deliveryPartner.service.port }}
      targetPort: http
      protocol: TCP
      name: http-delivery
  selector:
    {{- include "grocery-app.selectorLabels" (dict "context" . "component" "delivery-partner") | nindent 4 }}
{{- end }}
