{{- if .Values.productService.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "grocery-app.componentName" (dict "context" . "component" "product-service") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "grocery-app.componentLabels" (dict "context" . "component" "product-service") | nindent 4 }}
spec:
  minAvailable: {{ .Values.productService.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "grocery-app.selectorLabels" (dict "context" . "component" "product-service") | nindent 6 }}
{{- end }}
