global:
  imagePullPolicy: IfNotPresent
  domain: grocery.example.com


# -- Set to false to use an external Redis instance
enabled: true
image:
  repository: redis
  tag: alpine
port: 6379
storage:
  size: 2Gi
  # -- Leave empty to use cluster default StorageClass
  storageClass: ""
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
nodeSelector: {}
tolerations: []
affinity: {}

# ---------------------------------------------------------------------------
# Secrets
# ---------------------------------------------------------------------------
